[IV-21-22] Objetivo 3
aleveji/BuscaRecetas pull request #11
Opened 2021-11-19 14:53 UTC by aleveji

2021-11-21 13:19 UTC, aleveji commented
Listo para revisión @JJ

2021-11-21 18:29 UTC, JJ requested changes
Un poco de coherencia en el uso de dependencias, por favor.

2021-11-21 18:29 UTC, JJ commented on docs/eleccion_gestor_tareas.md
> +viene incluido por defecto con Node.js y es muy completo, por lo que no tendré que instalar una dependencia extra para el gestor de tareas.
Podías por lo menos haber comentado alternativas.

2021-11-21 18:29 UTC, JJ commented on package.json
> +    "check": "check-syntax app/ingrediente.js",
¿No instalas una dependencia adicional para el gestor de tareas y la instalas para comprobar la sintaxis?

2021-11-21 19:46 UTC, aleveji commented
Listo para revisión @JJ

2021-11-22 11:23 UTC, JJ approved these changes
:+1:

2021-11-22 11:29 UTC, merged