[IV-21-22] Objetivo 4
aleveji/BuscaRecetas pull request #13
Opened 2021-12-01 11:27 UTC by aleveji

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y de
   *framework* de test?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

2021-12-01 15:44 UTC, aleveji commented
Listo para revisión @JJ

2021-12-07 17:30 UTC, JJ requested changes
Problema principal: ni hay lógica de negocio, ni la testeas. Problemas adicionales sobre las herramientas elegidas y el hecho de que el milestone lo has asignado a voleo en vez de molestarte en incluir lo que surja de este objetivo en el producto mínimamente viable.

2021-12-07 17:30 UTC, JJ commented on app/ingrediente.js
> +        return "Ingrediente -> " + this.nombre + " [Calorias: " + this.calorias + ", Grasas: " + this.grasas + ", Hidratos: " + this.hidratos + ", Proteinas: " + this.proteinas + "]";
Esto sería mucho más fácil si usaras un diccionario.

2021-12-07 17:30 UTC, JJ commented on app/test/test.js
> +    describe('Getters', function() {
No estás testeando ninguna lógica de negocio. Está bien que testees, para dejar el interfaz fijado, pero lo que se pide en este objetivo es que se testee la lógica de negocio.

2021-12-07 17:30 UTC, JJ commented on docs/eleccion_framework_test.md
> +por Mocha ya que es uno de los frameworks más antiguos y cuenta con una gran comunidad. Además, trás
Dices antiguo, leo viejo. No solamente tienes que elegir un test runner, sino también una biblioteca de aserciones. Mira los errores frecuentes de la semana 13 para ver cómo hacer una elección técnica.

2021-12-15 19:11 UTC, JJ commented
Ping?

2021-12-17 17:27 UTC, aleveji commented
Listo para revisión @JJ

2021-12-17 19:21 UTC, JJ requested changes
Te perdonaría lo de que no has puesto los criterios de elección ni las diferentes opciones por la originalidad de usar aqa, pero es que también tienes que tratar de testear la lógica de negocio, no solo creación de objetos, así que del tirón haz los dos, porfa.

2021-12-17 19:21 UTC, JJ commented on package.json
> +    "aqa": "^1.2.14"
Es una dependencia de desarrollo.

2021-12-17 20:08 UTC, aleveji commented
> Te perdonaría lo de que no has puesto los criterios de elección ni las diferentes opciones por la originalidad de usar aqa, pero es que también tienes que tratar de testear la lógica de negocio, no solo creación de objetos, así que del tirón haz los dos, porfa.

Para testear la lógica de negocio lo que hecho ha sido una función que maximiza las proteínas en función de las calorías como me comentaste el otro día en clase. ¿No sería suficiente con esto? :thinking:

2021-12-19 07:59 UTC, JJ approved these changes
OK, aprobado, pero como te he dicho si cambias las cosas comentadas antes del siguiente, mejor.

2021-12-19 07:59 UTC, JJ commented on app/test/test.js
> +    t.deepEqual(ingrediente.maxProteinas(ingredientes,100).toString(),"Lechuga,Tomate,Piña","La funcion maxProteinas no funciona correctamente");
OK, ya lo veo. El mensaje debe ser en positivo

2022-01-10 12:27 UTC, merged